server {

    server_name localhost;
    listen 443 ssl;

    ssl_certificate /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/private.key; 

    location /websocket {
        proxy_pass http://myapp:8080;
        proxy_http_version 1.1;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Upgrade $http_upgrade;
    }

    location /public/ {
        alias /app/public/;
    }

    location /register {
        proxy_http_version 1.1;
        if ($request_method = "POST") {
            proxy_pass http://auth:8081;
            break;
        }
        proxy_pass http://myapp:8080;
    }

    location /login {
        proxy_http_version 1.1;
        if ($request_method = "POST") {
            proxy_pass http://auth:8081;
            break;
        }
        proxy_pass http://myapp:8080;
    }

    location /logout {
        proxy_pass http://auth:8081;
        proxy_http_version 1.1;
    }   

    location /api/users/settings {
        proxy_pass http://auth:8081;
        proxy_http_version 1.1;
    }

    location / {
        proxy_pass http://myapp:8080;
        proxy_http_version 1.1;
    }

}

server {
    server_name localhost;
    listen 80;

    location / {
        return 301 https://localhost$request_uri;
    }
}